# This file allows you to configure your python environment quickly for prednet.
# Please refer to the conda documentation for more info:
# https://conda.io/docs/user-guide/tasks/manage-environments.html

name: deployment

channels:
  - conda-forge

dependencies:
  - python=3.6
  - pip

  - pip:
    - azureml-sdk
    - hickle
    - sklearn
